### ISSUE TITLE
Need help on Egg Server

### ISSUE THREAD

**Issue by mattma** [mattma/tester#1]
Here in the [configuation](https://github.com/mattma/tester/blob/master/config/config.default.js#L7), it defined the **egg static** directory is `/app/dist/` folder, and **egg-view-nunjucks** default root path is the same.

In my [router.js](https://github.com/mattma/tester/blob/master/app/router.js#L4), when I query FE the link `localhost:4200/en`, it should render the [English Version of the html](https://github.com/mattma/tester/blob/master/app/controller/en.js#L4). When I do `localhost:4200/zh-cn`, it should render [chinese version of html](https://github.com/mattma/tester/blob/master/app/controller/cn.js#L4). 

Note: use [base attribute](https://github.com/mattma/tester/blob/master/app/dist/en/index.html#L6) to cap all of resources under `/en/` path.

The current issue is, if you start the server by `npm start`, you navigate to `localhost:4200`, it loads English version, Great. Then try load with `localhost:4200/zh-cn`, it does not work, got `404 Not Found` error, any idea?

**Comment by mattma** [comment]
@atian25 help? thanks

**Comment by atian25** [comment]
seem like your router is `app.get('/zh', 'cn');` not `/zh-cn`
